language: "node_js"
node_js:
  - "11"
  - "10"
  - "9"
  - "8"
  - "7"
  - "6"


before_install:
  - "npm install istanbul@0.4.x"
  - "npm install coveralls@2.x.x"

script:
  - "make test-cov"

after_success:
  - "make report-cov"

sudo: false
